/*
generated by generate-polyfill.js

modules:
["core-js/es"]

exclude:
["es.typed-array"]

targets:
{
  "edge": "88",
  "firefox": "78",
  "chrome": "87",
  "safari": "13"
}
*/

import 'core-js/modules/es.aggregate-error.js'
/*
{
  "firefox": "78",
  "safari": "13"
}
*/

import 'core-js/modules/es.aggregate-error.cause.js'
/*
{
  "chrome": "87",
  "edge": "88",
  "firefox": "78",
  "safari": "13"
}
*/

import 'core-js/modules/es.array.at.js'
/*
{
  "chrome": "87",
  "edge": "88",
  "firefox": "78",
  "safari": "13"
}
*/

import 'core-js/modules/es.array.find-last.js'
/*
{
  "chrome": "87",
  "edge": "88",
  "firefox": "78",
  "safari": "13"
}
*/

import 'core-js/modules/es.array.find-last-index.js'
/*
{
  "chrome": "87",
  "edge": "88",
  "firefox": "78",
  "safari": "13"
}
*/

import 'core-js/modules/es.array.includes.js'
/*
{
  "firefox": "78"
}
*/

import 'core-js/modules/es.array.push.js'
/*
{
  "chrome": "87",
  "edge": "88",
  "safari": "13"
}
*/

import 'core-js/modules/es.array.unshift.js'
/*
{
  "safari": "13"
}
*/

import 'core-js/modules/es.error.cause.js'
/*
{
  "chrome": "87",
  "edge": "88",
  "firefox": "78",
  "safari": "13"
}
*/

import 'core-js/modules/es.number.to-exponential.js'
/*
{
  "firefox": "78"
}
*/

import 'core-js/modules/es.object.has-own.js'
/*
{
  "chrome": "87",
  "edge": "88",
  "firefox": "78",
  "safari": "13"
}
*/

import 'core-js/modules/es.promise.any.js'
/*
{
  "firefox": "78",
  "safari": "13"
}
*/

import 'core-js/modules/es.promise.finally.js'
/*
{
  "safari": "13"
}
*/

import 'core-js/modules/es.reflect.to-string-tag.js'
/*
{
  "firefox": "78",
  "safari": "13"
}
*/

import 'core-js/modules/es.regexp.flags.js'
/*
{
  "chrome": "87",
  "edge": "88"
}
*/

import 'core-js/modules/es.string.at-alternative.js'
/*
{
  "chrome": "87",
  "edge": "88",
  "firefox": "78",
  "safari": "13"
}
*/

import 'core-js/modules/es.string.match-all.js'
/*
{
  "safari": "13"
}
*/

import 'core-js/modules/es.string.replace.js'
/*
{
  "safari": "13"
}
*/

import 'core-js/modules/es.string.replace-all.js'
/*
{
  "safari": "13"
}
*/

